[package]
name = "thegame"
version = "0.4.8"
authors = ["root"]

[dependencies]
rand = "0.4.*"
cursive = { git = "https://github.com/gyscos/Cursive.git" }
#decorators = { git = "https://github.com/Virtuos86/rust-decorators.git" }